{
 "title": "Vehicle Dynamics",
 "time": { "from": "now-30s", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Input", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Brake",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"socket_listener\")\n  |> filter(fn: (r) => r[\"_field\"] == \"brake\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Throttle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"socket_listener\")\n  |> filter(fn: (r) => r[\"_field\"] == \"throttle_human\" or r[\"_field\"] == \"throttle_dv\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Steering Angle",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"socket_listener\")\n  |> filter(fn: (r) => r[\"_field\"] == \"steering_angle\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Velocity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Velocity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"socket_listener\")\n  |> filter(fn: (r) => r[\"_field\"] == \"actual_velocity_kmh\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Accellerations and Omegas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Accellerations",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "m/s²" } },
     "targets": [
      {
       "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"socket_listener\")\n  |> filter(fn: (r) => r[\"_field\"] == \"acceleration_x\" or r[\"_field\"] == \"acceleration_y\" or r[\"_field\"] == \"acceleration_z\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Omegas",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 84 },
     "targets": [
      {
       "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"socket_listener\")\n  |> filter(fn: (r) => r[\"_field\"] == \"omega_x\" or r[\"_field\"] == \"omega_y\" or r[\"_field\"] == \"omega_z\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Suspensions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front Suspensions",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 228 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "targets": [
      {
       "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"socket_listener\")\n  |> filter(fn: (r) => r[\"_field\"] == \"suspensions_fl\" or r[\"_field\"] == \"suspensions_fr\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Rear Suspensions",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 246 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "targets": [
      {
       "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"socket_listener\")\n  |> filter(fn: (r) => r[\"_field\"] == \"suspensions_rl\" or r[\"_field\"] == \"suspensions_rr\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Brake Pressures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 229 },
     "targets": [
      {
       "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"socket_listener\")\n  |> filter(fn: (r) => r[\"_field\"] == \"brake_press_front\" or r[\"_field\"] == \"brake_press_rear\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Implausability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 230 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"socket_listener\")\n  |> filter(fn: (r) => r[\"_field\"] == \"driver_impls\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  }
 ]
}