services:
  # Database
  db:
    image: 'influxdb:2'
    volumes:
      - data-influx:/var/lib/influxdb2
      - config-influx:/etc/influxdb2
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpasswd
      - DOCKER_INFLUXDB_INIT_ORG=raceup
      - DOCKER_INFLUXDB_INIT_BUCKET=telemetry
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=1mYfOXFlghYobqZSq6Indjf1d3Tf7gECrZWAcm4EmqZB_pX6KKBIuEiaK3Wr2nQwBT3vzMXdW1DFK6zV5SKm-A==
    networks:
      - telemetry

  # Telegraf
  broker:
    image: 'telegraf:1.30'
    depends_on:
      - grafana-init
      - db
    environment:
      - GRAFANA_TOKEN_FILE=/run/shared/service-account-token.txt
    volumes:
      - ./config/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./config/telegraf/secret:/run/shared:ro
      - ./config/telegraf/init/init.sh:/ready.sh
    networks:
      - telemetry
    ports:
      - 8080:8080
      - "8094:8094/udp"
    entrypoint: ["/bin/sh", "/ready.sh"]

  # Grafana
  dashboard:
    image: 'grafana/grafana-enterprise'
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
      - ./config/grafana/dashboards/telemetry_live:/var/lib/grafana/dashboards/telemetry_live
      - ./config/grafana/dashboards/telemetry_stored:/var/lib/grafana/dashboards/telemetry_stored
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=a
      - GF_SERVER_ROOT_URL=http://telemetryed.raceup.it/
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=100ms
      - GF_INSTALL_PLUGINS=grafana-github-datasource
    networks:
      - telemetry

  #setting grafana
  grafana-init:
    image: alpine:latest
    depends_on:
      - dashboard
    volumes:
      - ./config/grafana/init/init_grafana.sh:/etc/grafana/init-grafana.sh:ro
      - ./config/telegraf/secret:/run/shared:rw
    networks:
      - telemetry
    entrypoint: ["/bin/sh", "/etc/grafana/init-grafana.sh"]

volumes:
  data-influx:
  config-influx:

networks:
  telemetry:
    driver: bridge
